// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6h87mrXBNFo_uR-Fq6MY0ARKU3t9Sq24',
    appId: '1:673548070209:web:47fe241bdae35c5b4ac5c0',
    messagingSenderId: '673548070209',
    projectId: 'todotask-89f33',
    authDomain: 'todotask-89f33.firebaseapp.com',
    storageBucket: 'todotask-89f33.firebasestorage.app',
    measurementId: 'G-SBXGNTB7GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChCipIPCpmkJP__GsoYxG9zMdmqhZrE6s',
    appId: '1:673548070209:android:e31e78a34bf288ca4ac5c0',
    messagingSenderId: '673548070209',
    projectId: 'todotask-89f33',
    storageBucket: 'todotask-89f33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vE1xVl60erVyobBng6w2tvfI2ZVzn4o',
    appId: '1:673548070209:ios:c87a08c1f82f34044ac5c0',
    messagingSenderId: '673548070209',
    projectId: 'todotask-89f33',
    storageBucket: 'todotask-89f33.firebasestorage.app',
    iosBundleId: 'com.example.todotask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5vE1xVl60erVyobBng6w2tvfI2ZVzn4o',
    appId: '1:673548070209:ios:c87a08c1f82f34044ac5c0',
    messagingSenderId: '673548070209',
    projectId: 'todotask-89f33',
    storageBucket: 'todotask-89f33.firebasestorage.app',
    iosBundleId: 'com.example.todotask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6h87mrXBNFo_uR-Fq6MY0ARKU3t9Sq24',
    appId: '1:673548070209:web:49d6302b0c9d20d24ac5c0',
    messagingSenderId: '673548070209',
    projectId: 'todotask-89f33',
    authDomain: 'todotask-89f33.firebaseapp.com',
    storageBucket: 'todotask-89f33.firebasestorage.app',
    measurementId: 'G-8PR2V14R92',
  );
}
